### PR TITLE
utilize paper player profiles

### PR DESCRIPTION
**Pull request by jeffschulthies**
Not sure what the proper way to do this is. I want to utilize fancy fireworks as a dependency to one of the plugins I'm developing. I tried adding the dependency using jitpack but it had problems compiling. This would utilize the paper api instead of using the internal mojang libraries for profiles.

### CODE REVIEW

**Comment by fantahund** [comment]
Unfortunately, I can not accept the so a the plugin is then no longer Spigot compatible. Will tonight but still care about a solution that it builds with the spigot api and not with spigot.

**Comment by jeffschulthies** [comment]
Yeah understood I'll just run a fork for now just wanted to toss some ideas out there

**Comment by fantahund** [comment]
But do you want to tell me what you need the plugin for as a dependency? :>

**Comment by jeffschulthies** [comment]
Yes! I have some minigames that I'd like to add more fanfair too and I really enjoy the fountains that are provided

**Comment by fantahund** [comment]
So now the plugin builds with the spigot api. And just for info a version other than java 17 makes no sense. ^^

**Comment by jeffschulthies** [comment]
thanks for the tweak. just wondering what's the reasoning behind not having anything other than java 17? I'm super rusty on my Java

**Comment by fantahund** [comment]
Weil Spigot/Paper Server nur mit Java 1.17 starten ^^
The normal 1.18 Minecraft servers and Minecraft clients also require Java 17.

**Comment by fantahund** [comment]
1.18 Minecraft servers and Minecraft clients also require Java 17.

**Comment by jeffschulthies** [comment]
@fantahund this is the idea of what I'm going for. I played around with removing the armorstand requirement since I just want to spawn the particle effects. [gif](https://imgur.com/aW2Bjm9)

**Comment by fantahund** [comment]
Just had a look at it. It is not so easy to change the system so that you only spawn the fireworks without armor stands.

**Comment by jeffschulthies** [comment]
Yeah I hacked something together in my fork for my use case just wanted to share how I'll be using it since I saw the comments on your spigot post https://www.spigotmc.org/resources/fancyfirework.98809/reviews about customizing defaults, etc

**Comment by fantahund** [comment]
^^

**Pull request closed without merging**
